export { LoginView } from "./auth/login";
export { DashboardView } from "./dashboard";
export { HrDepartmentView } from "./departments/hr/sections";
export { HrPerformanceView } from "./departments/hr";
export { ProjectsView, ProjectPlaceholderView } from "./departments/projects";
export { FinanceView } from "./departments/finance";
export { EmployeeProfileView } from "./employees/profile";
export { EmployeeInsightsView } from "./employees/insights";
export { SettingsView } from "./settings";
export { ProfileView } from "./profile";
export { NotFoundView, ServerErrorView } from "./errors";
